require("spec.helpers.setup")

local config = require("agentwatch.config")

describe("config", function()

  describe("_gitignore_glob_to_pattern", function()

    describe("simple patterns", function()
      it("matches literal filename", function()
        local pattern = config._gitignore_glob_to_pattern("foo.txt")
        assert.is_truthy(("foo.txt"):match(pattern))
        assert.is_falsy(("bar.txt"):match(pattern))
      end)

      it("escapes dots", function()
        local pattern = config._gitignore_glob_to_pattern("init.lua")
        assert.is_truthy(("init.lua"):match(pattern))
        assert.is_falsy(("initXlua"):match(pattern))
      end)

      it("trims whitespace", function()
        local pattern = config._gitignore_glob_to_pattern("  foo.txt  ")
        assert.is_truthy(("foo.txt"):match(pattern))
      end)
    end)

    describe("single star (*)", function()
      it("matches wildcard in filename", function()
        local pattern = config._gitignore_glob_to_pattern("*.log")
        assert.is_truthy(("debug.log"):match(pattern))
        assert.is_truthy(("error.log"):match(pattern))
        assert.is_falsy(("log"):match(pattern))
      end)

      it("star does not match slash character", function()
        -- The * matches any char except /, but pattern can match at any depth
        local pattern = config._gitignore_glob_to_pattern("log*.txt")
        assert.is_truthy(("logfile.txt"):match(pattern))
        assert.is_falsy(("log/file.txt"):match(pattern))  -- * doesn't match the slash
      end)

      it("matches at any path depth", function()
        local pattern = config._gitignore_glob_to_pattern("*.log")
        -- gitignore *.log matches debug.log anywhere in tree
        assert.is_truthy(("debug.log"):match(pattern))
        assert.is_truthy(("logs/debug.log"):match(pattern))
        assert.is_truthy(("foo/bar/debug.log"):match(pattern))
      end)
    end)

    describe("double star (**)", function()
      it("matches any directory depth with **/", function()
        local pattern = config._gitignore_glob_to_pattern("**/logs")
        assert.is_truthy(("logs"):match(pattern))
        assert.is_truthy(("foo/logs"):match(pattern))
        assert.is_truthy(("foo/bar/logs"):match(pattern))
      end)

      it("matches contents with /**", function()
        local pattern = config._gitignore_glob_to_pattern("logs/**")
        assert.is_truthy(("logs/debug.log"):match(pattern))
        assert.is_truthy(("logs/foo/bar.log"):match(pattern))
      end)
    end)

    describe("question mark (?)", function()
      it("matches single character", function()
        local pattern = config._gitignore_glob_to_pattern("debug?.log")
        assert.is_truthy(("debug1.log"):match(pattern))
        assert.is_truthy(("debuga.log"):match(pattern))
        assert.is_falsy(("debug.log"):match(pattern))
        assert.is_falsy(("debug12.log"):match(pattern))
      end)

      it("does not match path separator", function()
        local pattern = config._gitignore_glob_to_pattern("debug?.log")
        assert.is_falsy(("debug/.log"):match(pattern))
      end)
    end)

    describe("leading slash (anchored)", function()
      it("anchors pattern to root", function()
        local pattern = config._gitignore_glob_to_pattern("/build")
        assert.is_truthy(("build"):match(pattern))
        assert.is_falsy(("foo/build"):match(pattern))
      end)

      it("works with wildcards", function()
        local pattern = config._gitignore_glob_to_pattern("/*.log")
        assert.is_truthy(("debug.log"):match(pattern))
        assert.is_falsy(("foo/debug.log"):match(pattern))
      end)
    end)

    describe("trailing slash (directory)", function()
      it("matches as path component", function()
        local pattern = config._gitignore_glob_to_pattern("build/")
        assert.is_truthy(("foo/build/bar.js"):match(pattern))
        assert.is_truthy(("/build/file.txt"):match(pattern))
        assert.is_falsy(("build_backup/file.txt"):match(pattern))
      end)
    end)

    describe("character classes", function()
      it("preserves [0-9] range", function()
        local pattern = config._gitignore_glob_to_pattern("report.[0-9]*.json")
        assert.is_truthy(("report.1.json"):match(pattern))
        assert.is_truthy(("report.123.json"):match(pattern))
        assert.is_falsy(("report.abc.json"):match(pattern))
      end)

      it("preserves [a-z] range", function()
        local pattern = config._gitignore_glob_to_pattern("file_[a-z].txt")
        assert.is_truthy(("file_a.txt"):match(pattern))
        assert.is_truthy(("file_z.txt"):match(pattern))
        assert.is_falsy(("file_1.txt"):match(pattern))
      end)

      it("handles multiple character classes", function()
        local pattern = config._gitignore_glob_to_pattern("[a-z][0-9].log")
        assert.is_truthy(("a1.log"):match(pattern))
        assert.is_truthy(("z9.log"):match(pattern))
        assert.is_falsy(("11.log"):match(pattern))
      end)
    end)

    describe("common gitignore patterns", function()
      it("matches node_modules as path component", function()
        local pattern = config._gitignore_glob_to_pattern("node_modules")
        assert.is_truthy(("foo/node_modules/bar.js"):match(pattern))
        assert.is_truthy(("/node_modules/react/index.js"):match(pattern))
        assert.is_falsy(("node_modules_backup/file.js"):match(pattern))
      end)

      it("matches .env files", function()
        local pattern = config._gitignore_glob_to_pattern(".env*")
        assert.is_truthy((".env"):match(pattern))
        assert.is_truthy((".env.local"):match(pattern))
        assert.is_truthy((".env.production"):match(pattern))
      end)

      it("matches dist directory as path component", function()
        local pattern = config._gitignore_glob_to_pattern("dist/")
        assert.is_truthy(("foo/dist/bundle.js"):match(pattern))
        assert.is_truthy(("/dist/index.js"):match(pattern))
      end)

      it("matches __pycache__ as path component", function()
        local pattern = config._gitignore_glob_to_pattern("__pycache__")
        assert.is_truthy(("src/__pycache__/module.pyc"):match(pattern))
        assert.is_truthy(("/__pycache__/foo.pyc"):match(pattern))
      end)

      it("matches *.pyc files", function()
        local pattern = config._gitignore_glob_to_pattern("*.pyc")
        assert.is_truthy(("module.pyc"):match(pattern))
        assert.is_truthy(("src/module.pyc"):match(pattern))
      end)
    end)

  end)

end)
